# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OuraApi.Api.RingConfigurationRoutes do
  @moduledoc """
  API calls for all endpoints tagged `RingConfigurationRoutes`.
  """

  alias OuraApi.Connection
  import OuraApi.RequestBuilder

  @doc """
  Multiple Ring Configuration Documents

  ### Parameters

  - `connection` (OuraApi.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:next_token` (String.t):

  ### Returns

  - `{:ok, OuraApi.Model.MultiDocumentResponseRingConfigurationModel.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec multiple_ring_configuration_documents_v2_usercollection_ring_configuration_get(Tesla.Env.client, keyword()) :: {:ok, nil} | {:ok, OuraApi.Model.HttpValidationError.t} | {:ok, OuraApi.Model.MultiDocumentResponseRingConfigurationModel.t} | {:error, Tesla.Env.t}
  def multiple_ring_configuration_documents_v2_usercollection_ring_configuration_get(connection, opts \\ []) do
    optional_params = %{
      :next_token => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/v2/usercollection/ring_configuration")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, OuraApi.Model.MultiDocumentResponseRingConfigurationModel},
      {400, false},
      {401, false},
      {403, false},
      {429, false},
      {422, OuraApi.Model.HttpValidationError}
    ])
  end

  @doc """
  Single Ring Configuration Document

  ### Parameters

  - `connection` (OuraApi.Connection): Connection to server
  - `document_id` (String.t):
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, OuraApi.Model.RingConfigurationModel.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec single_ring_configuration_document_v2_usercollection_ring_configuration_document_id_get(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:ok, OuraApi.Model.RingConfigurationModel.t} | {:ok, OuraApi.Model.HttpValidationError.t} | {:error, Tesla.Env.t}
  def single_ring_configuration_document_v2_usercollection_ring_configuration_document_id_get(connection, document_id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/v2/usercollection/ring_configuration/#{document_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, OuraApi.Model.RingConfigurationModel},
      {404, false},
      {400, false},
      {401, false},
      {403, false},
      {429, false},
      {422, OuraApi.Model.HttpValidationError}
    ])
  end
end
