# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OuraApi.Model.CreateWebhookSubscriptionRequest do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :callback_url,
    :verification_token,
    :event_type,
    :data_type
  ]

  @type t :: %__MODULE__{
    :callback_url => String.t,
    :verification_token => String.t,
    :event_type => OuraApi.Model.WebhookOperation.t,
    :data_type => OuraApi.Model.ExtApiV2DataType.t
  }

  alias OuraApi.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:event_type, :struct, OuraApi.Model.WebhookOperation)
     |> Deserializer.deserialize(:data_type, :struct, OuraApi.Model.ExtApiV2DataType)
  end
end
