# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OuraApi.Model.DailySleepModel do
  @moduledoc """
  Object defining daily sleep.
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :contributors,
    :day,
    :score,
    :timestamp
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :contributors => OuraApi.Model.SleepContributors.t,
    :day => Date.t,
    :score => integer() | nil,
    :timestamp => String.t
  }

  alias OuraApi.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:contributors, :struct, OuraApi.Model.SleepContributors)
     |> Deserializer.deserialize(:day, :date, nil)
  end
end
