# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OuraApi.Model.DailyStressModel do
  @moduledoc """
  Object defining daily stress.
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :day,
    :stress_high,
    :recovery_high,
    :day_summary
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :day => Date.t,
    :stress_high => integer() | nil,
    :recovery_high => integer() | nil,
    :day_summary => OuraApi.Model.DailyStressSummary.t | nil
  }

  alias OuraApi.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:day, :date, nil)
     |> Deserializer.deserialize(:day_summary, :struct, OuraApi.Model.DailyStressSummary)
  end
end
