# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OuraApi.Model.DailySpO2AggregatedValuesModel do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :average
  ]

  @type t :: %__MODULE__{
    :average => float()
  }

  def decode(value) do
    value
  end
end
