# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OuraApi.Model.DailySpO2Model do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :day,
    :spo2_percentage
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :day => Date.t,
    :spo2_percentage => OuraApi.Model.DailySpO2AggregatedValuesModel.t | nil
  }

  alias OuraApi.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:day, :date, nil)
     |> Deserializer.deserialize(:spo2_percentage, :struct, OuraApi.Model.DailySpO2AggregatedValuesModel)
  end
end
