# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OuraApi.Model.EnhancedTagModel do
  @moduledoc """
  An EnhancedTagModel maps an ASSATag. An ASSATag in ExtAPIV2 is called a EnhancedTag An EnhancedTagModel will be populated by data from an ASSATag The fields in the EnhancedTagModel map to fields in an ASSATag
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :tag_type_code,
    :start_time,
    :end_time,
    :start_day,
    :end_day,
    :comment
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :tag_type_code => String.t | nil,
    :start_time => String.t,
    :end_time => String.t | nil,
    :start_day => Date.t,
    :end_day => Date.t | nil,
    :comment => String.t | nil
  }

  alias OuraApi.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:start_day, :date, nil)
     |> Deserializer.deserialize(:end_day, :date, nil)
  end
end
