# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OuraApi.Model.HeartRateResponse do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :data,
    :next_token
  ]

  @type t :: %__MODULE__{
    :data => [OuraApi.Model.HeartRateModel.t],
    :next_token => String.t | nil
  }

  alias OuraApi.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:data, :list, OuraApi.Model.HeartRateModel)
  end
end
