# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OuraApi.Model.HeartRateModel do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :bpm,
    :source,
    :timestamp
  ]

  @type t :: %__MODULE__{
    :bpm => integer(),
    :source => OuraApi.Model.HeartRateSource.t,
    :timestamp => String.t
  }

  alias OuraApi.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:source, :struct, OuraApi.Model.HeartRateSource)
  end
end
