# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OuraApi.Model.HttpValidationError do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :detail
  ]

  @type t :: %__MODULE__{
    :detail => [OuraApi.Model.ValidationError.t] | nil
  }

  alias OuraApi.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:detail, :list, OuraApi.Model.ValidationError)
  end
end
