# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OuraApi.Model.ReadinessContributors do
  @moduledoc """
  Object defining readiness score contributors.
  """

  @derive Jason.Encoder
  defstruct [
    :activity_balance,
    :body_temperature,
    :hrv_balance,
    :previous_day_activity,
    :previous_night,
    :recovery_index,
    :resting_heart_rate,
    :sleep_balance
  ]

  @type t :: %__MODULE__{
    :activity_balance => integer() | nil,
    :body_temperature => integer() | nil,
    :hrv_balance => integer() | nil,
    :previous_day_activity => integer() | nil,
    :previous_night => integer() | nil,
    :recovery_index => integer() | nil,
    :resting_heart_rate => integer() | nil,
    :sleep_balance => integer() | nil
  }

  def decode(value) do
    value
  end
end
