# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OuraApi.Model.RestModeEpisode do
  @moduledoc """
  Object defining a Rest Mode episode.
  """

  @derive Jason.Encoder
  defstruct [
    :tags,
    :timestamp
  ]

  @type t :: %__MODULE__{
    :tags => [String.t],
    :timestamp => String.t
  }

  def decode(value) do
    value
  end
end
