# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OuraApi.Model.RestModePeriodModel do
  @moduledoc """
  Object contains information about rest mode episode.
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :end_day,
    :end_time,
    :episodes,
    :start_day,
    :start_time
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :end_day => Date.t | nil,
    :end_time => String.t | nil,
    :episodes => [OuraApi.Model.RestModeEpisode.t],
    :start_day => Date.t,
    :start_time => String.t
  }

  alias OuraApi.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:end_day, :date, nil)
     |> Deserializer.deserialize(:episodes, :list, OuraApi.Model.RestModeEpisode)
     |> Deserializer.deserialize(:start_day, :date, nil)
  end
end
