# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OuraApi.Model.RingConfigurationModel do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :color,
    :design,
    :firmware_version,
    :hardware_type,
    :set_up_at,
    :size
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :color => OuraApi.Model.RingColor.t | nil,
    :design => OuraApi.Model.RingDesign.t | nil,
    :firmware_version => String.t | nil,
    :hardware_type => OuraApi.Model.RingHardwareType.t | nil,
    :set_up_at => String.t | nil,
    :size => integer() | nil
  }

  alias OuraApi.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:color, :struct, OuraApi.Model.RingColor)
     |> Deserializer.deserialize(:design, :struct, OuraApi.Model.RingDesign)
     |> Deserializer.deserialize(:hardware_type, :struct, OuraApi.Model.RingHardwareType)
  end
end
