# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OuraApi.Model.Sample do
  @moduledoc """
  Object defining a recorded sample.
  """

  @derive Jason.Encoder
  defstruct [
    :interval,
    :items,
    :timestamp
  ]

  @type t :: %__MODULE__{
    :interval => float(),
    :items => [float() | nil],
    :timestamp => String.t
  }

  def decode(value) do
    value
  end
end
