# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OuraApi.Model.SessionModel do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :day,
    :start_datetime,
    :end_datetime,
    :type,
    :heart_rate,
    :heart_rate_variability,
    :mood,
    :motion_count
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :day => Date.t,
    :start_datetime => String.t,
    :end_datetime => String.t,
    :type => OuraApi.Model.MomentType.t,
    :heart_rate => OuraApi.Model.Sample.t | nil,
    :heart_rate_variability => OuraApi.Model.Sample.t | nil,
    :mood => OuraApi.Model.MomentMood.t | nil,
    :motion_count => OuraApi.Model.Sample.t | nil
  }

  alias OuraApi.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:day, :date, nil)
     |> Deserializer.deserialize(:type, :struct, OuraApi.Model.MomentType)
     |> Deserializer.deserialize(:heart_rate, :struct, OuraApi.Model.Sample)
     |> Deserializer.deserialize(:heart_rate_variability, :struct, OuraApi.Model.Sample)
     |> Deserializer.deserialize(:mood, :struct, OuraApi.Model.MomentMood)
     |> Deserializer.deserialize(:motion_count, :struct, OuraApi.Model.Sample)
  end
end
