# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OuraApi.Model.SleepContributors do
  @moduledoc """
  Object defining sleep score contributors.
  """

  @derive Jason.Encoder
  defstruct [
    :deep_sleep,
    :efficiency,
    :latency,
    :rem_sleep,
    :restfulness,
    :timing,
    :total_sleep
  ]

  @type t :: %__MODULE__{
    :deep_sleep => integer() | nil,
    :efficiency => integer() | nil,
    :latency => integer() | nil,
    :rem_sleep => integer() | nil,
    :restfulness => integer() | nil,
    :timing => integer() | nil,
    :total_sleep => integer() | nil
  }

  def decode(value) do
    value
  end
end
