# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OuraApi.Model.TagModel do
  @moduledoc """
  A TagModel maps to an ASSANote. An ASSANote in ExtAPIV2 is called a Tag A TagModel will be populated by data from an ASSANote The fields in the TagModel map to fields in an ASSANote
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :day,
    :text,
    :timestamp,
    :tags
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :day => Date.t,
    :text => String.t | nil,
    :timestamp => DateTime.t,
    :tags => [String.t]
  }

  alias OuraApi.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:day, :date, nil)
     |> Deserializer.deserialize(:timestamp, :datetime, nil)
  end
end
