# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OuraApi.Model.ValidationError do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :loc,
    :msg,
    :type
  ]

  @type t :: %__MODULE__{
    :loc => [OuraApi.Model.ValidationErrorLocInner.t],
    :msg => String.t,
    :type => String.t
  }

  alias OuraApi.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:loc, :list, OuraApi.Model.ValidationErrorLocInner)
  end
end
