# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OuraApi.Model.WebhookSubscriptionModel do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :callback_url,
    :event_type,
    :data_type,
    :expiration_time
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :callback_url => String.t,
    :event_type => OuraApi.Model.WebhookOperation.t,
    :data_type => OuraApi.Model.ExtApiV2DataType.t,
    :expiration_time => DateTime.t
  }

  alias OuraApi.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:event_type, :struct, OuraApi.Model.WebhookOperation)
     |> Deserializer.deserialize(:data_type, :struct, OuraApi.Model.ExtApiV2DataType)
     |> Deserializer.deserialize(:expiration_time, :datetime, nil)
  end
end
